"""modulos

Revision ID: 7b6ef2a96f07
Revises: 
Create Date: 2026-10-01 12:27:16.767145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6ef2a96f07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('chave', sa.String(length=120), nullable=False),
    sa.Column('potencia_w', sa.Float(), nullable=False),
    sa.Column('altura_m', sa.Float(), nullable=False),
    sa.Column('largura_m', sa.Float(), nullable=False),
    sa.Column('espessura_m', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave', name='uq_modulos_chave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modulos')
    # ### end Alembic commands ###
