// <auto-generated>
// Gerado por tools/gerar-comandos-traduzidos.py a partir de
// src/Clivus.Core/CommandNames.cs. Não editar à mão: mude a tabela e rode o
// script.
// </auto-generated>
using Autodesk.AutoCAD.Runtime;

[assembly: CommandClass(typeof(Clivus.Plugin.ComandosTraduzidos))]

namespace Clivus.Plugin;

/// <summary>
/// Os nomes digitáveis em inglês e espanhol (etapa 10, 10.5): cada um chama o
/// mesmo método, com as mesmas opções, do comando global em português.
/// </summary>
public static class ComandosTraduzidos
{
    [CommandMethod("CLIVUS_ALIGNMENT")]
    public static void CLIVUS_ALIGNMENT() => AlignmentCommands.Alinhamento();

    [CommandMethod("CLIVUS_ALINEACION")]
    public static void CLIVUS_ALINEACION() => AlignmentCommands.Alinhamento();

    [CommandMethod("CLIVUS_ALIGNMENTS")]
    public static void CLIVUS_ALIGNMENTS() => AlignmentCommands.Alinhamentos();

    [CommandMethod("CLIVUS_ALINEACIONES")]
    public static void CLIVUS_ALINEACIONES() => AlignmentCommands.Alinhamentos();

    [CommandMethod("CLIVUS_HEIGHTS")]
    public static void CLIVUS_HEIGHTS() => FileiraCommands.Alturas();

    [CommandMethod("CLIVUS_HEIGHTS_REGENERATE")]
    public static void CLIVUS_HEIGHTS_REGENERATE() => AlturasCommands.Regerar();

    [CommandMethod("CLIVUS_ALTURAS_REGENERAR")]
    public static void CLIVUS_ALTURAS_REGENERAR() => AlturasCommands.Regerar();

    [CommandMethod("CLIVUS_ANALYSES")]
    public static void CLIVUS_ANALYSES() => JanelasDeAnaliseCommands.Analises();

    [CommandMethod("CLIVUS_ANALISIS")]
    public static void CLIVUS_ANALISIS() => JanelasDeAnaliseCommands.Analises();

    [CommandMethod("CLIVUS_ANALYSES_PARAMETERS")]
    public static void CLIVUS_ANALYSES_PARAMETERS() => AnalisesCommands.Parametros();

    [CommandMethod("CLIVUS_ANALISIS_PARAMETROS")]
    public static void CLIVUS_ANALISIS_PARAMETROS() => AnalisesCommands.Parametros();

    [CommandMethod("CLIVUS_AN_SLOPE_ANALYZE")]
    public static void CLIVUS_AN_SLOPE_ANALYZE() => AnalisesIndependentesCommands.DeclAnalisar();

    [CommandMethod("CLIVUS_AN_PEND_ANALIZAR")]
    public static void CLIVUS_AN_PEND_ANALIZAR() => AnalisesIndependentesCommands.DeclAnalisar();

    [CommandMethod("CLIVUS_AN_SLOPE_ERASE")]
    public static void CLIVUS_AN_SLOPE_ERASE() => AnalisesIndependentesCommands.DeclApagar();

    [CommandMethod("CLIVUS_AN_PEND_BORRAR")]
    public static void CLIVUS_AN_PEND_BORRAR() => AnalisesIndependentesCommands.DeclApagar();

    [CommandMethod("CLIVUS_AN_SLOPE_COLORS")]
    public static void CLIVUS_AN_SLOPE_COLORS() => AnalisesIndependentesCommands.DeclCores();

    [CommandMethod("CLIVUS_AN_PEND_COLORES")]
    public static void CLIVUS_AN_PEND_COLORES() => AnalisesIndependentesCommands.DeclCores();

    [CommandMethod("CLIVUS_AN_SLOPE_INSERT")]
    public static void CLIVUS_AN_SLOPE_INSERT() => AnalisesIndependentesCommands.DeclInserir();

    [CommandMethod("CLIVUS_AN_PEND_INSERTAR")]
    public static void CLIVUS_AN_PEND_INSERTAR() => AnalisesIndependentesCommands.DeclInserir();

    [CommandMethod("CLIVUS_AN_SLOPE_QUANTIFY")]
    public static void CLIVUS_AN_SLOPE_QUANTIFY() => AnalisesIndependentesCommands.DeclQuantificar();

    [CommandMethod("CLIVUS_AN_PEND_CUANTIFICAR")]
    public static void CLIVUS_AN_PEND_CUANTIFICAR() => AnalisesIndependentesCommands.DeclQuantificar();

    [CommandMethod("CLIVUS_AN_HE_ANALYZE")]
    public static void CLIVUS_AN_HE_ANALYZE() => AnalisesIndependentesCommands.PaAnalisar();

    [CommandMethod("CLIVUS_AN_BS_ANALIZAR")]
    public static void CLIVUS_AN_BS_ANALIZAR() => AnalisesIndependentesCommands.PaAnalisar();

    [CommandMethod("CLIVUS_AN_HE_ERASE")]
    public static void CLIVUS_AN_HE_ERASE() => AnalisesIndependentesCommands.PaApagar();

    [CommandMethod("CLIVUS_AN_BS_BORRAR")]
    public static void CLIVUS_AN_BS_BORRAR() => AnalisesIndependentesCommands.PaApagar();

    [CommandMethod("CLIVUS_AN_HE_COLORS")]
    public static void CLIVUS_AN_HE_COLORS() => AnalisesIndependentesCommands.PaCores();

    [CommandMethod("CLIVUS_AN_BS_COLORES")]
    public static void CLIVUS_AN_BS_COLORES() => AnalisesIndependentesCommands.PaCores();

    [CommandMethod("CLIVUS_AN_HE_INSERT")]
    public static void CLIVUS_AN_HE_INSERT() => AnalisesIndependentesCommands.PaInserir();

    [CommandMethod("CLIVUS_AN_BS_INSERTAR")]
    public static void CLIVUS_AN_BS_INSERTAR() => AnalisesIndependentesCommands.PaInserir();

    [CommandMethod("CLIVUS_AN_HE_QUANTIFY")]
    public static void CLIVUS_AN_HE_QUANTIFY() => AnalisesIndependentesCommands.PaQuantificar();

    [CommandMethod("CLIVUS_AN_BS_CUANTIFICAR")]
    public static void CLIVUS_AN_BS_CUANTIFICAR() => AnalisesIndependentesCommands.PaQuantificar();

    [CommandMethod("CLIVUS_AN_LE_ANALYZE")]
    public static void CLIVUS_AN_LE_ANALYZE() => AnalisesIndependentesCommands.PbAnalisar();

    [CommandMethod("CLIVUS_AN_BI_ANALIZAR")]
    public static void CLIVUS_AN_BI_ANALIZAR() => AnalisesIndependentesCommands.PbAnalisar();

    [CommandMethod("CLIVUS_AN_LE_ERASE")]
    public static void CLIVUS_AN_LE_ERASE() => AnalisesIndependentesCommands.PbApagar();

    [CommandMethod("CLIVUS_AN_BI_BORRAR")]
    public static void CLIVUS_AN_BI_BORRAR() => AnalisesIndependentesCommands.PbApagar();

    [CommandMethod("CLIVUS_AN_LE_COLORS")]
    public static void CLIVUS_AN_LE_COLORS() => AnalisesIndependentesCommands.PbCores();

    [CommandMethod("CLIVUS_AN_BI_COLORES")]
    public static void CLIVUS_AN_BI_COLORES() => AnalisesIndependentesCommands.PbCores();

    [CommandMethod("CLIVUS_AN_LE_INSERT")]
    public static void CLIVUS_AN_LE_INSERT() => AnalisesIndependentesCommands.PbInserir();

    [CommandMethod("CLIVUS_AN_BI_INSERTAR")]
    public static void CLIVUS_AN_BI_INSERTAR() => AnalisesIndependentesCommands.PbInserir();

    [CommandMethod("CLIVUS_AN_LE_QUANTIFY")]
    public static void CLIVUS_AN_LE_QUANTIFY() => AnalisesIndependentesCommands.PbQuantificar();

    [CommandMethod("CLIVUS_AN_BI_CUANTIFICAR")]
    public static void CLIVUS_AN_BI_CUANTIFICAR() => AnalisesIndependentesCommands.PbQuantificar();

    [CommandMethod("CLIVUS_AN_EMBED_INSERT")]
    public static void CLIVUS_AN_EMBED_INSERT() => AnalisesIndependentesCommands.PilarEnterradoInserir();

    [CommandMethod("CLIVUS_AN_EMPOT_INSERTAR")]
    public static void CLIVUS_AN_EMPOT_INSERTAR() => AnalisesIndependentesCommands.PilarEnterradoInserir();

    [CommandMethod("CLIVUS_AN_PILE_ANALYZE")]
    public static void CLIVUS_AN_PILE_ANALYZE() => AnalisesIndependentesCommands.PilarAnalisar();

    [CommandMethod("CLIVUS_AN_PILOTE_ANALIZAR")]
    public static void CLIVUS_AN_PILOTE_ANALIZAR() => AnalisesIndependentesCommands.PilarAnalisar();

    [CommandMethod("CLIVUS_AN_PILE_ERASE")]
    public static void CLIVUS_AN_PILE_ERASE() => AnalisesIndependentesCommands.PilarApagar();

    [CommandMethod("CLIVUS_AN_PILOTE_BORRAR")]
    public static void CLIVUS_AN_PILOTE_BORRAR() => AnalisesIndependentesCommands.PilarApagar();

    [CommandMethod("CLIVUS_AN_PILE_COLORS")]
    public static void CLIVUS_AN_PILE_COLORS() => AnalisesIndependentesCommands.PilarCores();

    [CommandMethod("CLIVUS_AN_PILOTE_COLORES")]
    public static void CLIVUS_AN_PILOTE_COLORES() => AnalisesIndependentesCommands.PilarCores();

    [CommandMethod("CLIVUS_AN_PILE_INSERT")]
    public static void CLIVUS_AN_PILE_INSERT() => AnalisesIndependentesCommands.PilarInserir();

    [CommandMethod("CLIVUS_AN_PILOTE_INSERTAR")]
    public static void CLIVUS_AN_PILOTE_INSERTAR() => AnalisesIndependentesCommands.PilarInserir();

    [CommandMethod("CLIVUS_AN_PILE_QUANTIFY")]
    public static void CLIVUS_AN_PILE_QUANTIFY() => AnalisesIndependentesCommands.PilarQuantificar();

    [CommandMethod("CLIVUS_AN_PILOTE_CUANTIFICAR")]
    public static void CLIVUS_AN_PILOTE_CUANTIFICAR() => AnalisesIndependentesCommands.PilarQuantificar();

    [CommandMethod("CLIVUS_AN_PILELEN_INSERT")]
    public static void CLIVUS_AN_PILELEN_INSERT() => AnalisesIndependentesCommands.PilarTotalInserir();

    [CommandMethod("CLIVUS_AN_PILOTELONG_INSERTAR")]
    public static void CLIVUS_AN_PILOTELONG_INSERTAR() => AnalisesIndependentesCommands.PilarTotalInserir();

    [CommandMethod("CLIVUS_AN_TEST_PARTS")]
    public static void CLIVUS_AN_TEST_PARTS() => AnalisesIndependentesCommands.TestePecas();

    [CommandMethod("CLIVUS_AN_PRUEBA_PIEZAS")]
    public static void CLIVUS_AN_PRUEBA_PIEZAS() => AnalisesIndependentesCommands.TestePecas();

    [CommandMethod("CLIVUS_ERASE_ALL", CommandFlags.UsePickSet)]
    public static void CLIVUS_ERASE_ALL() => ApagarTudoCommands.ApagarTudo();

    [CommandMethod("CLIVUS_BORRAR_TODO", CommandFlags.UsePickSet)]
    public static void CLIVUS_BORRAR_TODO() => ApagarTudoCommands.ApagarTudo();

    [CommandMethod("CLIVUS_TREE")]
    public static void CLIVUS_TREE() => ArvoreCommands.Arvore();

    [CommandMethod("CLIVUS_ARBOL")]
    public static void CLIVUS_ARBOL() => ArvoreCommands.Arvore();

    [CommandMethod("CLIVUS_ACTIVATE")]
    public static void CLIVUS_ACTIVATE() => AtivarCommands.Ativar();

    [CommandMethod("CLIVUS_ACTIVAR")]
    public static void CLIVUS_ACTIVAR() => AtivarCommands.Ativar();

    [CommandMethod("CLIVUS_TESTBENCH")]
    public static void CLIVUS_TESTBENCH() => BancadaCommands.Bancada();

    [CommandMethod("CLIVUS_BANCO_PRUEBAS")]
    public static void CLIVUS_BANCO_PRUEBAS() => BancadaCommands.Bancada();

    [CommandMethod("CLIVUS_PARAMETERS")]
    public static void CLIVUS_PARAMETERS() => ConfigCommands.Config();

    [CommandMethod("CLIVUS_PARAMETROS")]
    public static void CLIVUS_PARAMETROS() => ConfigCommands.Config();

    [CommandMethod("CLIVUS_SETTINGS")]
    public static void CLIVUS_SETTINGS() => ConfiguracoesCommands.Configuracoes();

    [CommandMethod("CLIVUS_CONFIGURACION")]
    public static void CLIVUS_CONFIGURACION() => ConfiguracoesCommands.Configuracoes();

    [CommandMethod("CLIVUS_PARAMETERS_STATUS")]
    public static void CLIVUS_PARAMETERS_STATUS() => ConfigCommands.ConfigStatus();

    [CommandMethod("CLIVUS_PARAMETROS_ESTADO")]
    public static void CLIVUS_PARAMETROS_ESTADO() => ConfigCommands.ConfigStatus();

    [CommandMethod("CLIVUS_PARAMETERS_TEST")]
    public static void CLIVUS_PARAMETERS_TEST() => ConfigCommands.ConfigTeste();

    [CommandMethod("CLIVUS_PARAMETROS_PRUEBA")]
    public static void CLIVUS_PARAMETROS_PRUEBA() => ConfigCommands.ConfigTeste();

    [CommandMethod("CLIVUS_SLOPE")]
    public static void CLIVUS_SLOPE() => DeclividadeCommands.Declividade();

    [CommandMethod("CLIVUS_INCLINACION")]
    public static void CLIVUS_INCLINACION() => DeclividadeCommands.Declividade();

    [CommandMethod("CLIVUS_ELECTRICAL")]
    public static void CLIVUS_ELECTRICAL() => ConfiguracaoEletricaCommands.Eletrica();

    [CommandMethod("CLIVUS_ELECTRICA")]
    public static void CLIVUS_ELECTRICA() => ConfiguracaoEletricaCommands.Eletrica();

    [CommandMethod("CLIVUS_ELECTRICAL_SUMMARY")]
    public static void CLIVUS_ELECTRICAL_SUMMARY() => ResumoEletricoCommands.Resumo();

    [CommandMethod("CLIVUS_ELECTRICA_RESUMEN")]
    public static void CLIVUS_ELECTRICA_RESUMEN() => ResumoEletricoCommands.Resumo();

    [CommandMethod("CLIVUS_STATUS", CommandFlags.Modal | CommandFlags.NoUndoMarker)]
    public static void CLIVUS_STATUS() => EstadoCommands.Estado();

    [CommandMethod("CLIVUS_STYLES")]
    public static void CLIVUS_STYLES() => EstilosCommands.Estilos();

    [CommandMethod("CLIVUS_EXPORT", CommandFlags.UsePickSet)]
    public static void CLIVUS_EXPORT() => ExportCommands.Exportar();

    [CommandMethod("CLIVUS_ROW")]
    public static void CLIVUS_ROW() => FileiraCommands.Fileira();

    [CommandMethod("CLIVUS_FILA")]
    public static void CLIVUS_FILA() => FileiraCommands.Fileira();

    [CommandMethod("CLIVUS_GROUPS", CommandFlags.Modal | CommandFlags.NoUndoMarker)]
    public static void CLIVUS_GROUPS() => GrupoCommands.Listar();

    [CommandMethod("CLIVUS_GROUPS_PANEL", CommandFlags.Modal | CommandFlags.NoUndoMarker)]
    public static void CLIVUS_GROUPS_PANEL() => GrupoCommands.Painel();

    [CommandMethod("CLIVUS_GRUPOS_PANEL", CommandFlags.Modal | CommandFlags.NoUndoMarker)]
    public static void CLIVUS_GRUPOS_PANEL() => GrupoCommands.Painel();

    [CommandMethod("CLIVUS_GROUP_ERASE")]
    public static void CLIVUS_GROUP_ERASE() => GrupoCommands.Apagar();

    [CommandMethod("CLIVUS_GRUPO_BORRAR")]
    public static void CLIVUS_GRUPO_BORRAR() => GrupoCommands.Apagar();

    [CommandMethod("CLIVUS_GROUP_CREATE", CommandFlags.UsePickSet)]
    public static void CLIVUS_GROUP_CREATE() => GrupoCommands.Criar();

    [CommandMethod("CLIVUS_GRUPO_CREAR", CommandFlags.UsePickSet)]
    public static void CLIVUS_GRUPO_CREAR() => GrupoCommands.Criar();

    [CommandMethod("CLIVUS_GROUP_RECALCULATE")]
    public static void CLIVUS_GROUP_RECALCULATE() => GrupoCommands.Recalcular();

    [CommandMethod("CLIVUS_GROUP_SELECT", CommandFlags.Modal | CommandFlags.NoUndoMarker)]
    public static void CLIVUS_GROUP_SELECT() => GrupoCommands.Selecionar();

    [CommandMethod("CLIVUS_GRUPO_SELECCIONAR", CommandFlags.Modal | CommandFlags.NoUndoMarker)]
    public static void CLIVUS_GRUPO_SELECCIONAR() => GrupoCommands.Selecionar();

    [CommandMethod("CLIVUS_LANGUAGE")]
    public static void CLIVUS_LANGUAGE() => IdiomaCommands.Idioma();

    [CommandMethod("CLIVUS_KWP_SELECTION", CommandFlags.Modal | CommandFlags.UsePickSet | CommandFlags.NoUndoMarker)]
    public static void CLIVUS_KWP_SELECTION() => SelecaoCommands.KwpDaSelecao();

    [CommandMethod("CLIVUS_KWP_SELECCION", CommandFlags.Modal | CommandFlags.UsePickSet | CommandFlags.NoUndoMarker)]
    public static void CLIVUS_KWP_SELECCION() => SelecaoCommands.KwpDaSelecao();

    [CommandMethod("CLIVUS_LOCATION")]
    public static void CLIVUS_LOCATION() => GeoCommands.Localizacao();

    [CommandMethod("CLIVUS_UBICACION")]
    public static void CLIVUS_UBICACION() => GeoCommands.Localizacao();

    [CommandMethod("CLIVUS_TABLE")]
    public static void CLIVUS_TABLE() => MesaCommands.Mesa();

    [CommandMethod("CLIVUS_MIGRATE")]
    public static void CLIVUS_MIGRATE() => MigracaoDoNome.Migrar();

    [CommandMethod("CLIVUS_NUMBER")]
    public static void CLIVUS_NUMBER() => NumerarCommands.Numerar();

    [CommandMethod("CLIVUS_HELLO")]
    public static void CLIVUS_HELLO() => ClivusCommands.Ola();

    [CommandMethod("CLIVUS_HOLA")]
    public static void CLIVUS_HOLA() => ClivusCommands.Ola();

    [CommandMethod("CLIVUS_PENDING")]
    public static void CLIVUS_PENDING() => EstadoCommands.Sujar();

    [CommandMethod("CLIVUS_PENDIENTE")]
    public static void CLIVUS_PENDIENTE() => EstadoCommands.Sujar();

    [CommandMethod("CLIVUS_PAINT")]
    public static void CLIVUS_PAINT() => AnalisesCommands.Pintar();

    [CommandMethod("CLIVUS_ENDS", CommandFlags.UsePickSet)]
    public static void CLIVUS_ENDS() => PontasCommands.Pontas();

    [CommandMethod("CLIVUS_EXTREMOS", CommandFlags.UsePickSet)]
    public static void CLIVUS_EXTREMOS() => PontasCommands.Pontas();

    [CommandMethod("CLIVUS_RECALCULATE", CommandFlags.UsePickSet)]
    public static void CLIVUS_RECALCULATE() => RecalcularCommands.Recalcular();

    [CommandMethod("CLIVUS_RECALCULATE_PENDING")]
    public static void CLIVUS_RECALCULATE_PENDING() => RecalcularCommands.RecalcularSujas();

    [CommandMethod("CLIVUS_RECALCULAR_PENDIENTES")]
    public static void CLIVUS_RECALCULAR_PENDIENTES() => RecalcularCommands.RecalcularSujas();

    [CommandMethod("CLIVUS_RECOUNT")]
    public static void CLIVUS_RECOUNT() => RecontarCommands.Recontar();

    [CommandMethod("CLIVUS_REGENERATE_AREA", CommandFlags.UsePickSet)]
    public static void CLIVUS_REGENERATE_AREA() => RefazerCommands.Refazer();

    [CommandMethod("CLIVUS_REGENERAR_AREA", CommandFlags.UsePickSet)]
    public static void CLIVUS_REGENERAR_AREA() => RefazerCommands.Refazer();

    [CommandMethod("CLIVUS_REGENERATE_ALL")]
    public static void CLIVUS_REGENERATE_ALL() => AnalisesCommands.Regerar();

    [CommandMethod("CLIVUS_REGENERAR_TODO")]
    public static void CLIVUS_REGENERAR_TODO() => AnalisesCommands.Regerar();

    [CommandMethod("CLIVUS_REGENERATE_ROW", CommandFlags.UsePickSet)]
    public static void CLIVUS_REGENERATE_ROW() => TrocarMesaCommands.RegerarFileira();

    [CommandMethod("CLIVUS_REGENERAR_FILA", CommandFlags.UsePickSet)]
    public static void CLIVUS_REGENERAR_FILA() => TrocarMesaCommands.RegerarFileira();

    [CommandMethod("CLIVUS_REINDEX")]
    public static void CLIVUS_REINDEX() => ReindexCommands.Reindexar();

    [CommandMethod("CLIVUS_RENAME_BLOCKS")]
    public static void CLIVUS_RENAME_BLOCKS() => RenomearCommands.Renomear();

    [CommandMethod("CLIVUS_RENOMBRAR_BLOQUES")]
    public static void CLIVUS_RENOMBRAR_BLOQUES() => RenomearCommands.Renomear();

    [CommandMethod("CLIVUS_ABOUT")]
    public static void CLIVUS_ABOUT() => SobreCommands.Sobre();

    [CommandMethod("CLIVUS_ACERCA")]
    public static void CLIVUS_ACERCA() => SobreCommands.Sobre();

    [CommandMethod("CLIVUS_SHADOWS")]
    public static void CLIVUS_SHADOWS() => SombrasCommands.Sombras();

    [CommandMethod("CLIVUS_SHADOWS_ERASE")]
    public static void CLIVUS_SHADOWS_ERASE() => SombrasCommands.SombrasApagar();

    [CommandMethod("CLIVUS_SOMBRAS_BORRAR")]
    public static void CLIVUS_SOMBRAS_BORRAR() => SombrasCommands.SombrasApagar();

    [CommandMethod("CLIVUS_ETIQUETAS")]
    public static void CLIVUS_ETIQUETAS() => JanelasDeAnaliseCommands.Tags();

    [CommandMethod("CLIVUS_TAG_ROWS")]
    public static void CLIVUS_TAG_ROWS() => TagsCommands.FileirasInserir();

    [CommandMethod("CLIVUS_ETIQ_FILAS")]
    public static void CLIVUS_ETIQ_FILAS() => TagsCommands.FileirasInserir();

    [CommandMethod("CLIVUS_TAG_ROWS_ERASE")]
    public static void CLIVUS_TAG_ROWS_ERASE() => TagsCommands.FileirasApagar();

    [CommandMethod("CLIVUS_ETIQ_FILAS_BORRAR")]
    public static void CLIVUS_ETIQ_FILAS_BORRAR() => TagsCommands.FileirasApagar();

    [CommandMethod("CLIVUS_TAG_TABLES")]
    public static void CLIVUS_TAG_TABLES() => TagsCommands.MesasInserir();

    [CommandMethod("CLIVUS_ETIQ_MESAS")]
    public static void CLIVUS_ETIQ_MESAS() => TagsCommands.MesasInserir();

    [CommandMethod("CLIVUS_TAG_TABLES_ERASE")]
    public static void CLIVUS_TAG_TABLES_ERASE() => TagsCommands.MesasApagar();

    [CommandMethod("CLIVUS_ETIQ_MESAS_BORRAR")]
    public static void CLIVUS_ETIQ_MESAS_BORRAR() => TagsCommands.MesasApagar();

    [CommandMethod("CLIVUS_TAG_MODULES")]
    public static void CLIVUS_TAG_MODULES() => TagsCommands.ModulosInserir();

    [CommandMethod("CLIVUS_ETIQ_MODULOS")]
    public static void CLIVUS_ETIQ_MODULOS() => TagsCommands.ModulosInserir();

    [CommandMethod("CLIVUS_TAG_MODULES_ERASE")]
    public static void CLIVUS_TAG_MODULES_ERASE() => TagsCommands.ModulosApagar();

    [CommandMethod("CLIVUS_ETIQ_MODULOS_BORRAR")]
    public static void CLIVUS_ETIQ_MODULOS_BORRAR() => TagsCommands.ModulosApagar();

    [CommandMethod("CLIVUS_ETIQ_STRINGS")]
    public static void CLIVUS_ETIQ_STRINGS() => TagsCommands.StringsInserir();

    [CommandMethod("CLIVUS_TAG_STRINGS_ERASE")]
    public static void CLIVUS_TAG_STRINGS_ERASE() => TagsCommands.StringsApagar();

    [CommandMethod("CLIVUS_ETIQ_STRINGS_BORRAR")]
    public static void CLIVUS_ETIQ_STRINGS_BORRAR() => TagsCommands.StringsApagar();

    [CommandMethod("CLIVUS_TERRAIN")]
    public static void CLIVUS_TERRAIN() => TerrainCommands.Terreno();

    [CommandMethod("CLIVUS_TERRAIN_SUMMARY")]
    public static void CLIVUS_TERRAIN_SUMMARY() => TerrenoResumoCommands.Resumo();

    [CommandMethod("CLIVUS_TERRENO_RESUMEN")]
    public static void CLIVUS_TERRENO_RESUMEN() => TerrenoResumoCommands.Resumo();

    [CommandMethod("CLIVUS_TERRAIN_STATUS")]
    public static void CLIVUS_TERRAIN_STATUS() => TerrainCommands.TerrenoStatus();

    [CommandMethod("CLIVUS_TERRENO_ESTADO")]
    public static void CLIVUS_TERRENO_ESTADO() => TerrainCommands.TerrenoStatus();

    [CommandMethod("CLIVUS_SWAP_TABLE", CommandFlags.UsePickSet)]
    public static void CLIVUS_SWAP_TABLE() => TrocarMesaCommands.Trocar();

    [CommandMethod("CLIVUS_CAMBIAR_MESA", CommandFlags.UsePickSet)]
    public static void CLIVUS_CAMBIAR_MESA() => TrocarMesaCommands.Trocar();

    [CommandMethod("CLIVUS_PLANT")]
    public static void CLIVUS_PLANT() => UsinaCommands.Usina();

    [CommandMethod("CLIVUS_PLANTA")]
    public static void CLIVUS_PLANTA() => UsinaCommands.Usina();

    [CommandMethod("CLIVUS_VALIDATE", CommandFlags.Modal | CommandFlags.NoUndoMarker)]
    public static void CLIVUS_VALIDATE() => ValidarCommands.Validar();
}
