"""Gera src/Clivus.Plugin/ComandosTraduzidos.cs (etapa 10, 10.5).

Os nomes digitáveis em inglês e espanhol de cada comando (tabela em
src/Clivus.Core/CommandNames.cs) viram comandos declarados como os outros,
cada um chamando o mesmo método, com as mesmas opções, do comando global em
português. Registrar em tempo de execução (Utils.AddCommand) derrubava o Core
Console na abertura do plugin; declarado, vale em todo host e o teste de
nível 2 alcança.

    python tools/gerar-comandos-traduzidos.py

Rodar depois de mudar a tabela ou acrescentar comando; o teste
CommandNamesTests confere que o arquivo gerado está em dia.
"""
import io
import os
import re
import sys

RAIZ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLUGIN = os.path.join(RAIZ, 'src', 'Clivus.Plugin')
SAIDA = os.path.join(PLUGIN, 'ComandosTraduzidos.cs')


def ler(caminho):
    with io.open(caminho, encoding='utf-8-sig') as f:
        return f.read()


def constantes():
    # O PluginInfo é partial (PluginInfo.cs e PluginInfo.Eletrica*.cs).
    core = os.path.join(RAIZ, 'src', 'Clivus.Core')
    texto = '\n'.join(ler(os.path.join(core, n)) for n in sorted(os.listdir(core)) if n.startswith('PluginInfo') and n.endswith('.cs'))
    return dict(re.findall(r'public const string (Comando\w+) = "(CLIVUS_[A-Z0-9_]+)"', texto))


def tabela():
    texto = ler(os.path.join(RAIZ, 'src', 'Clivus.Core', 'CommandNames.cs'))
    return {g: (en, es) for g, en, es in re.findall(r'\["(CLIVUS_\w+)"\] = \("(CLIVUS_\w+)", "(CLIVUS_\w+)"\)', texto)}


ATRIBUTO = re.compile(r'\[CommandMethod\(PluginInfo\.(Comando\w+)(?:,\s*([^)\]]+))?\)\]\s*(?:\[[^\]]*\]\s*)*public static void (\w+)\(\)')
CLASSE = re.compile(r'(?:public|internal)\s+(?:static\s+|sealed\s+|partial\s+)*class\s+(\w+)')


def alvos(consts):
    achados = {}
    for nome in sorted(os.listdir(PLUGIN)):
        if not nome.endswith('.cs') or nome == 'ComandosTraduzidos.cs':
            continue
        texto = ler(os.path.join(PLUGIN, nome))
        for m in ATRIBUTO.finditer(texto):
            classes = [c for c in CLASSE.finditer(texto, 0, m.start())]
            if not classes:
                continue
            classe = classes[-1].group(1)
            glob = consts.get(m.group(1))
            if glob:
                achados[glob] = (classe, m.group(3), (m.group(2) or '').strip())
    return achados


def gerar():
    consts = constantes()
    nomes = tabela()
    metodos = alvos(consts)

    faltam = sorted(g for g in nomes if g not in metodos)
    if faltam:
        sys.exit('comando da tabela sem método achado: ' + ', '.join(faltam))

    linhas = []
    feitos = set()
    for glob in sorted(nomes):
        classe, metodo, flags = metodos[glob]
        for local in dict.fromkeys(nomes[glob]):
            if local == glob or local in feitos:
                continue
            feitos.add(local)
            argumentos = f'"{local}"' + (f', {flags}' if flags else '')
            linhas.append(f'    [CommandMethod({argumentos})]')
            linhas.append(f'    public static void {local}() => {classe}.{metodo}();')
            linhas.append('')

    corpo = '\n'.join(linhas).rstrip() + '\n'
    texto = f'''// <auto-generated>
// Gerado por tools/gerar-comandos-traduzidos.py a partir de
// src/Clivus.Core/CommandNames.cs. Não editar à mão: mude a tabela e rode o
// script.
// </auto-generated>
using Autodesk.AutoCAD.Runtime;

[assembly: CommandClass(typeof(Clivus.Plugin.ComandosTraduzidos))]

namespace Clivus.Plugin;

/// <summary>
/// Os nomes digitáveis em inglês e espanhol (etapa 10, 10.5): cada um chama o
/// mesmo método, com as mesmas opções, do comando global em português.
/// </summary>
public static class ComandosTraduzidos
{{
{corpo}}}
'''
    with io.open(SAIDA, 'w', encoding='utf-8', newline='\n') as f:
        f.write(texto)
    print(f'{len(feitos)} nome(s) traduzido(s) em {os.path.relpath(SAIDA, RAIZ)}')


if __name__ == '__main__':
    gerar()
