namespace Clivus.Core;

/// <summary>
/// Os nomes digitáveis dos comandos em inglês e espanhol (etapa 10, 10.5;
/// Renan: "Se possível, comandos CAD também"). O nome global (português,
/// <c>CLIVUS_*</c>) não muda e vale sempre: é o que os botões, os scripts e os
/// testes usam. Os nomes em inglês e espanhol valem sempre, em qualquer
/// idioma da tela: são declarados em <c>ComandosTraduzidos.cs</c>, gerado por
/// <c>tools/gerar-comandos-traduzidos.py</c> a partir desta tabela.
/// Comandos de teste (<c>_AUTO</c>) não ganham nome traduzido.
/// </summary>
public static class CommandNames
{
    /// <summary>Nome global → (inglês, espanhol).</summary>
    public static IReadOnlyDictionary<string, (string En, string Es)> Table { get; } = new Dictionary<string, (string, string)>
    {
        ["CLIVUS_3D"] = ("CLIVUS_3D", "CLIVUS_3D"),
        ["CLIVUS_ALINHAMENTO"] = ("CLIVUS_ALIGNMENT", "CLIVUS_ALINEACION"),
        ["CLIVUS_ALINHAMENTOS"] = ("CLIVUS_ALIGNMENTS", "CLIVUS_ALINEACIONES"),
        ["CLIVUS_ALTURAS"] = ("CLIVUS_HEIGHTS", "CLIVUS_ALTURAS"),
        ["CLIVUS_ALTURAS_REGERAR"] = ("CLIVUS_HEIGHTS_REGENERATE", "CLIVUS_ALTURAS_REGENERAR"),
        ["CLIVUS_AN_DECL_ANALISAR"] = ("CLIVUS_AN_SLOPE_ANALYZE", "CLIVUS_AN_PEND_ANALIZAR"),
        ["CLIVUS_AN_DECL_APAGAR"] = ("CLIVUS_AN_SLOPE_ERASE", "CLIVUS_AN_PEND_BORRAR"),
        ["CLIVUS_AN_DECL_CORES"] = ("CLIVUS_AN_SLOPE_COLORS", "CLIVUS_AN_PEND_COLORES"),
        ["CLIVUS_AN_DECL_INSERIR"] = ("CLIVUS_AN_SLOPE_INSERT", "CLIVUS_AN_PEND_INSERTAR"),
        ["CLIVUS_AN_DECL_QUANTIFICAR"] = ("CLIVUS_AN_SLOPE_QUANTIFY", "CLIVUS_AN_PEND_CUANTIFICAR"),
        ["CLIVUS_AN_PA_ANALISAR"] = ("CLIVUS_AN_HE_ANALYZE", "CLIVUS_AN_BS_ANALIZAR"),
        ["CLIVUS_AN_PA_APAGAR"] = ("CLIVUS_AN_HE_ERASE", "CLIVUS_AN_BS_BORRAR"),
        ["CLIVUS_AN_PA_CORES"] = ("CLIVUS_AN_HE_COLORS", "CLIVUS_AN_BS_COLORES"),
        ["CLIVUS_AN_PA_INSERIR"] = ("CLIVUS_AN_HE_INSERT", "CLIVUS_AN_BS_INSERTAR"),
        ["CLIVUS_AN_PA_QUANTIFICAR"] = ("CLIVUS_AN_HE_QUANTIFY", "CLIVUS_AN_BS_CUANTIFICAR"),
        ["CLIVUS_AN_PB_ANALISAR"] = ("CLIVUS_AN_LE_ANALYZE", "CLIVUS_AN_BI_ANALIZAR"),
        ["CLIVUS_AN_PB_APAGAR"] = ("CLIVUS_AN_LE_ERASE", "CLIVUS_AN_BI_BORRAR"),
        ["CLIVUS_AN_PB_CORES"] = ("CLIVUS_AN_LE_COLORS", "CLIVUS_AN_BI_COLORES"),
        ["CLIVUS_AN_PB_INSERIR"] = ("CLIVUS_AN_LE_INSERT", "CLIVUS_AN_BI_INSERTAR"),
        ["CLIVUS_AN_PB_QUANTIFICAR"] = ("CLIVUS_AN_LE_QUANTIFY", "CLIVUS_AN_BI_CUANTIFICAR"),
        ["CLIVUS_AN_PENT_INSERIR"] = ("CLIVUS_AN_EMBED_INSERT", "CLIVUS_AN_EMPOT_INSERTAR"),
        ["CLIVUS_AN_PILAR_ANALISAR"] = ("CLIVUS_AN_PILE_ANALYZE", "CLIVUS_AN_PILOTE_ANALIZAR"),
        ["CLIVUS_AN_PILAR_APAGAR"] = ("CLIVUS_AN_PILE_ERASE", "CLIVUS_AN_PILOTE_BORRAR"),
        ["CLIVUS_AN_PILAR_CORES"] = ("CLIVUS_AN_PILE_COLORS", "CLIVUS_AN_PILOTE_COLORES"),
        ["CLIVUS_AN_PILAR_INSERIR"] = ("CLIVUS_AN_PILE_INSERT", "CLIVUS_AN_PILOTE_INSERTAR"),
        ["CLIVUS_AN_PILAR_QUANTIFICAR"] = ("CLIVUS_AN_PILE_QUANTIFY", "CLIVUS_AN_PILOTE_CUANTIFICAR"),
        ["CLIVUS_AN_PTOT_INSERIR"] = ("CLIVUS_AN_PILELEN_INSERT", "CLIVUS_AN_PILOTELONG_INSERTAR"),
        ["CLIVUS_AN_TESTE_PECAS"] = ("CLIVUS_AN_TEST_PARTS", "CLIVUS_AN_PRUEBA_PIEZAS"),
        ["CLIVUS_ANALISES"] = ("CLIVUS_ANALYSES", "CLIVUS_ANALISIS"),
        ["CLIVUS_ANALISES_PARAMETROS"] = ("CLIVUS_ANALYSES_PARAMETERS", "CLIVUS_ANALISIS_PARAMETROS"),
        ["CLIVUS_APAGAR"] = ("CLIVUS_ERASE", "CLIVUS_BORRAR"),
        ["CLIVUS_APAGAR_TUDO"] = ("CLIVUS_ERASE_ALL", "CLIVUS_BORRAR_TODO"),
        ["CLIVUS_AREA"] = ("CLIVUS_AREA", "CLIVUS_AREA"),
        ["CLIVUS_AREAS"] = ("CLIVUS_AREAS", "CLIVUS_AREAS"),
        ["CLIVUS_ARVORE"] = ("CLIVUS_TREE", "CLIVUS_ARBOL"),
        ["CLIVUS_ATIVAR"] = ("CLIVUS_ACTIVATE", "CLIVUS_ACTIVAR"),
        ["CLIVUS_BANCADA"] = ("CLIVUS_TESTBENCH", "CLIVUS_BANCO_PRUEBAS"),
        ["CLIVUS_CONFIG"] = ("CLIVUS_PARAMETERS", "CLIVUS_PARAMETROS"),
        ["CLIVUS_CONFIG_STATUS"] = ("CLIVUS_PARAMETERS_STATUS", "CLIVUS_PARAMETROS_ESTADO"),
        ["CLIVUS_CONFIG_TESTE"] = ("CLIVUS_PARAMETERS_TEST", "CLIVUS_PARAMETROS_PRUEBA"),
        ["CLIVUS_CONFIGURACOES"] = ("CLIVUS_SETTINGS", "CLIVUS_CONFIGURACION"),
        ["CLIVUS_COORD"] = ("CLIVUS_COORD", "CLIVUS_COORD"),
        ["CLIVUS_DECLIVIDADE"] = ("CLIVUS_SLOPE", "CLIVUS_INCLINACION"),
        ["CLIVUS_ELETRICA"] = ("CLIVUS_ELECTRICAL", "CLIVUS_ELECTRICA"),
        ["CLIVUS_ELETRICA_ALOCAR"] = ("CLIVUS_ELECTRICAL_ALLOCATE", "CLIVUS_ELECTRICA_ASIGNAR"),
        ["CLIVUS_ELETRICA_POSICIONAR"] = ("CLIVUS_ELECTRICAL_PLACE", "CLIVUS_ELECTRICA_UBICAR"),
        ["CLIVUS_ELETRICA_SELECIONAR"] = ("CLIVUS_ELECTRICAL_SELECT", "CLIVUS_ELECTRICA_SELECCIONAR"),
        ["CLIVUS_ELETRICA_SKID"] = ("CLIVUS_ELECTRICAL_SKID", "CLIVUS_ELECTRICA_SKID"),
        ["CLIVUS_ELETRICA_RESUMO"] = ("CLIVUS_ELECTRICAL_SUMMARY", "CLIVUS_ELECTRICA_RESUMEN"),
        ["CLIVUS_ESTADO"] = ("CLIVUS_STATUS", "CLIVUS_ESTADO"),
        ["CLIVUS_ESTILOS"] = ("CLIVUS_STYLES", "CLIVUS_ESTILOS"),
        ["CLIVUS_EXCEL"] = ("CLIVUS_EXCEL", "CLIVUS_EXCEL"),
        ["CLIVUS_EXPORTAR"] = ("CLIVUS_EXPORT", "CLIVUS_EXPORTAR"),
        ["CLIVUS_FILEIRA"] = ("CLIVUS_ROW", "CLIVUS_FILA"),
        ["CLIVUS_GRUPO_APAGAR"] = ("CLIVUS_GROUP_ERASE", "CLIVUS_GRUPO_BORRAR"),
        ["CLIVUS_GRUPO_CRIAR"] = ("CLIVUS_GROUP_CREATE", "CLIVUS_GRUPO_CREAR"),
        ["CLIVUS_GRUPO_RECALCULAR"] = ("CLIVUS_GROUP_RECALCULATE", "CLIVUS_GRUPO_RECALCULAR"),
        ["CLIVUS_GRUPO_SELECIONAR"] = ("CLIVUS_GROUP_SELECT", "CLIVUS_GRUPO_SELECCIONAR"),
        ["CLIVUS_GRUPOS"] = ("CLIVUS_GROUPS", "CLIVUS_GRUPOS"),
        ["CLIVUS_GRUPOS_PAINEL"] = ("CLIVUS_GROUPS_PANEL", "CLIVUS_GRUPOS_PANEL"),
        ["CLIVUS_IDIOMA"] = ("CLIVUS_LANGUAGE", "CLIVUS_IDIOMA"),
        ["CLIVUS_KWP_SELECAO"] = ("CLIVUS_KWP_SELECTION", "CLIVUS_KWP_SELECCION"),
        ["CLIVUS_LOCAL"] = ("CLIVUS_LOCATION", "CLIVUS_UBICACION"),
        ["CLIVUS_MESA"] = ("CLIVUS_TABLE", "CLIVUS_MESA"),
        ["CLIVUS_MIGRAR"] = ("CLIVUS_MIGRATE", "CLIVUS_MIGRAR"),
        ["CLIVUS_NUMERACAO"] = ("CLIVUS_STRING_NUMBERING", "CLIVUS_NUMERACION_STRINGS"),
        ["CLIVUS_NUMERAR"] = ("CLIVUS_NUMBER", "CLIVUS_NUMERAR"),
        ["CLIVUS_OLA"] = ("CLIVUS_HELLO", "CLIVUS_HOLA"),
        ["CLIVUS_PENDENTE"] = ("CLIVUS_PENDING", "CLIVUS_PENDIENTE"),
        ["CLIVUS_PINTAR"] = ("CLIVUS_PAINT", "CLIVUS_PINTAR"),
        ["CLIVUS_PONTAS"] = ("CLIVUS_ENDS", "CLIVUS_EXTREMOS"),
        ["CLIVUS_RECALCULAR"] = ("CLIVUS_RECALCULATE", "CLIVUS_RECALCULAR"),
        ["CLIVUS_RECALCULAR_PENDENTES"] = ("CLIVUS_RECALCULATE_PENDING", "CLIVUS_RECALCULAR_PENDIENTES"),
        ["CLIVUS_RECONTAR"] = ("CLIVUS_RECOUNT", "CLIVUS_RECONTAR"),
        ["CLIVUS_REFAZER"] = ("CLIVUS_REGENERATE_AREA", "CLIVUS_REGENERAR_AREA"),
        ["CLIVUS_REGERAR"] = ("CLIVUS_REGENERATE_ALL", "CLIVUS_REGENERAR_TODO"),
        ["CLIVUS_REGERAR_FILEIRA"] = ("CLIVUS_REGENERATE_ROW", "CLIVUS_REGENERAR_FILA"),
        ["CLIVUS_REINDEXAR"] = ("CLIVUS_REINDEX", "CLIVUS_REINDEXAR"),
        ["CLIVUS_RENOMEAR"] = ("CLIVUS_RENAME_BLOCKS", "CLIVUS_RENOMBRAR_BLOQUES"),
        ["CLIVUS_SOBRE"] = ("CLIVUS_ABOUT", "CLIVUS_ACERCA"),
        ["CLIVUS_SOMBRA_PORQUE"] = ("CLIVUS_SHADOW_WHY", "CLIVUS_SOMBRA_POR_QUE"),
        ["CLIVUS_SOMBRAS"] = ("CLIVUS_SHADOWS", "CLIVUS_SOMBRAS"),
        ["CLIVUS_SOMBRAS_APAGAR"] = ("CLIVUS_SHADOWS_ERASE", "CLIVUS_SOMBRAS_BORRAR"),
        ["CLIVUS_STRING"] = ("CLIVUS_STRING", "CLIVUS_STRING"),
        ["CLIVUS_STRING_GERAR"] = ("CLIVUS_STRING_GENERATE", "CLIVUS_STRING_GENERAR"),
        ["CLIVUS_STRING_MESAS"] = ("CLIVUS_STRING_TABLES", "CLIVUS_STRING_MESAS"),
        ["CLIVUS_TAG_FILEIRAS"] = ("CLIVUS_TAG_ROWS", "CLIVUS_ETIQ_FILAS"),
        ["CLIVUS_TAG_FILEIRAS_APAGAR"] = ("CLIVUS_TAG_ROWS_ERASE", "CLIVUS_ETIQ_FILAS_BORRAR"),
        ["CLIVUS_TAG_MESAS"] = ("CLIVUS_TAG_TABLES", "CLIVUS_ETIQ_MESAS"),
        ["CLIVUS_TAG_MESAS_APAGAR"] = ("CLIVUS_TAG_TABLES_ERASE", "CLIVUS_ETIQ_MESAS_BORRAR"),
        ["CLIVUS_TAG_MODULOS"] = ("CLIVUS_TAG_MODULES", "CLIVUS_ETIQ_MODULOS"),
        ["CLIVUS_TAG_MODULOS_APAGAR"] = ("CLIVUS_TAG_MODULES_ERASE", "CLIVUS_ETIQ_MODULOS_BORRAR"),
        ["CLIVUS_TAG_STRINGS"] = ("CLIVUS_TAG_STRINGS", "CLIVUS_ETIQ_STRINGS"),
        ["CLIVUS_TAG_STRINGS_APAGAR"] = ("CLIVUS_TAG_STRINGS_ERASE", "CLIVUS_ETIQ_STRINGS_BORRAR"),
        ["CLIVUS_TAGS"] = ("CLIVUS_TAGS", "CLIVUS_ETIQUETAS"),
        ["CLIVUS_TERRENO"] = ("CLIVUS_TERRAIN", "CLIVUS_TERRENO"),
        ["CLIVUS_TERRENO_RESUMO"] = ("CLIVUS_TERRAIN_SUMMARY", "CLIVUS_TERRENO_RESUMEN"),
        ["CLIVUS_TERRENO_STATUS"] = ("CLIVUS_TERRAIN_STATUS", "CLIVUS_TERRENO_ESTADO"),
        ["CLIVUS_TROCAR_MESA"] = ("CLIVUS_SWAP_TABLE", "CLIVUS_CAMBIAR_MESA"),
        ["CLIVUS_USINA"] = ("CLIVUS_PLANT", "CLIVUS_PLANTA"),
        ["CLIVUS_VALIDAR"] = ("CLIVUS_VALIDATE", "CLIVUS_VALIDAR"),
    };

    /// <summary>
    /// Todos os nomes de um comando: o global e os traduzidos. A trava da
    /// licença usa para deixar passar, em qualquer idioma, os comandos livres
    /// (sem isso, CLIVUS_ACTIVATE seria barrado sem licença).
    /// </summary>
    public static IEnumerable<string> AllNamesOf(string global)
    {
        yield return global;
        if (!Table.TryGetValue(global, out var nomes)) yield break;
        yield return nomes.En;
        yield return nomes.Es;
    }

    /// <summary>O nome no idioma, ou null quando é igual ao global (nada a registrar).</summary>
    public static string? LocalName(string global, UiLanguage idioma)
    {
        if (idioma == UiLanguage.Portuguese || !Table.TryGetValue(global, out var nomes)) return null;

        var local = idioma == UiLanguage.English ? nomes.En : nomes.Es;
        return string.Equals(local, global, StringComparison.OrdinalIgnoreCase) ? null : local;
    }
}
